msmbuilder/osprey

docs/conf.py
osprey/cross_validators.py
osprey/dataset_loaders.py
osprey/subclass_factory.py
osprey/tests/test_config.py

Add hook for msmbuilder dataset

Msmb dataset

---

.travis.yml
osprey/fit_estimator.py
osprey/strategies.py
osprey/subclass_factory.py
osprey/tests/test_strategies.py
osprey/utils.py

I copied over the function that was remove from sklearn 0.15

Fix breakage on sklearn-0.16

---

osprey/execute_plot.py

Bokeh has a completely new api for plotting things. This PR fixes that and specifies the version that was used.

Fix bokeh imports

---

osprey/fit_estimator.py

This should fix the ```_check_cv``` issue as raised in #89. I don't know what the exact test suite is so I don't know how to exactly update the help text.

fix sklearn issue

---

osprey/config.py
osprey/search_space.py
osprey/tests/test_config.py

This PR implements a jump search strategy method allowing parameters to be sampled with a particular jump. Its basically a small wrapper around the enumerate method thats already there .

Implemented jump search strategy

---

osprey/eval_scopes.py
osprey/execute_worker.py
osprey/fit_estimator.py

Add nice error message when training or test set contains zero elements

---

osprey/eval_scopes.py

re: https://github.com/msmbuilder/osprey/issues/105

fix pca ValueError

---

osprey/config.py
osprey/search_space.py
osprey/tests/test_config.py
osprey/tests/test_search_space.py

re: https://github.com/msmbuilder/osprey/issues/95

implement integer warping

---

osprey/config.py
osprey/execute_worker.py

re: https://github.com/msmbuilder/osprey/issues/23

added project_name filter for history

---

osprey/cli/parser_skeleton.py
osprey/data/sklearn_skeleton_config.yaml
osprey/execute_currentbest.py
osprey/execute_skeleton.py
osprey/tests/test_cli_worker_and_dump.py

re: https://github.com/msmbuilder/osprey/issues/121

modify current best

---

osprey/config.py
osprey/cross_validators.py
osprey/dataset_loaders.py
osprey/execute_worker.py
osprey/fit_estimator.py
osprey/utils.py

Simple fix for #123 
WIP because I didn't know what to do with internal `_num_samples` in `fit_estimator.py` (there is some custom logic for msmbuilder, which probably should be decoupled, but I am not sure how to do it)

Fix for #123

---

osprey/strategies.py
osprey/tests/test_strategies.py

Hello,
I needed to add GridSearch strategy in my case, and I guess in general user might want to go through all the options sometimes. Feel free to close the PR if you don't want to include this :) 
The naming might not be best, as I have to go in a circular fashion through all the options, but I wasn't sure how to name it differently

[Proposition] GridSearch strategy

---

osprey/config.py
osprey/search_space.py
osprey/tests/test_config.py

should fix #129. Also added functionality to accept a type so that the output is in the same format as required by the estimators

fix jump bug

---

devtools/conda-recipe/meta.yaml
osprey/data/msmbuilder_skeleton_config.yaml
osprey/tests/test_cli_worker_and_dump.py

re: https://github.com/msmbuilder/osprey/issues/112
This is going to fail until msmb v3.4 is up on conda.

added msmb test

---

.travis.yml
README.md
devtools/conda-recipe/meta.yaml

not sure if I'm doing this right....

adding coveralls

---

.travis.yml
devtools/conda-recipe/meta.yaml

re: https://github.com/msmbuilder/osprey/pull/131#issuecomment-204000095

keep tests in conda-build

---

devtools/conda-recipe/meta.yaml
osprey/execute_plot.py
osprey/plot.py
osprey/tests/test_cli_worker_and_dump.py

re: https://github.com/msmbuilder/osprey/issues/125
Also added a test and tried to reorganize the plotting methods into their own module.
*Sent from my :airplane:. Sorry for the brevity or unusual tone.*

Fix t-SNE plot

---

osprey/eval_scopes.py

re: https://github.com/msmbuilder/osprey/issues/142

stop tests from being imported

---

osprey/execute_currentbest.py
osprey/plot.py

re: https://github.com/msmbuilder/osprey/issues/138 and https://github.com/msmbuilder/osprey/issues/139

fix issues reported by jeiros

---

README.md

+ add Vijay, initials
+ fix MMS

fix citation

---

docs/index.rst

update add to toc

---

docs/index.rst

update fix link

---

docs/installation.rst

Proper code fencing

---

osprey/dataset_loaders.py
osprey/tests/test_dataset_loader.py

add delimiter-separated value dataset loader

add dsvloader

---

README.md
devtools/conda-recipe/meta.yaml
osprey/config.py
osprey/tests/test_cli_worker_and_dump.py
osprey/tests/test_config.py
osprey/utils.py
requirements.txt

re: https://github.com/msmbuilder/osprey/issues/188

add Config.trial_results

---

docs/getting_started.rst

add result docs

---

docs/getting_started.rst

fix code block

---

docs/getting_started.rst
osprey/cli/parser_worker.py
osprey/execute_worker.py
osprey/tests/test_cli_worker_and_dump.py

re: #195 and https://github.com/openjournals/joss-reviews/issues/34#issuecomment-240151698
allow user to specify random seed through CLI

specify random seed through CLI

---

docs/changelog.rst
osprey/execute_worker.py
osprey/fit_estimator.py
osprey/strategies.py

pass random_seed to estimator

---

.travis.yml

changing to this since it works well for mdentropy.

switch to ENV variables for AWS keys

---

osprey/search_space.py

I just cast the outputs as ints before I returned them. Very happy to use a better fix instead.

Hacky fix to make log with int work

---

devtools/conda-recipe/meta.yaml
docs/changelog.rst
osprey/cli/parser_worker.py
osprey/execute_worker.py
osprey/tests/test_cli_worker_and_dump.py

re: https://github.com/msmbuilder/osprey/issues/230

Add n_jobs argument to worker

---

.gitignore
docs/changelog.rst
osprey/search_space.py

Changed the mapping of the suggested value from the Gaussian Processes strategy to the integer variables so that the interval [0,1] is mapped symmetrically to the integer values.  
See [here](https://github.com/RobertArbon/IntegerMapping/blob/master/Integer%20Mapping.ipynb) for graphical example of the problem and the solution.

Fix point from gp

---

devtools/travis-ci/build_docs.sh
docs/requirements.txt

late to the game on this one: https://github.com/deepchem/deepchem/pull/814

pin numpydoc to 0.7

---

devtools/travis-ci/install_miniconda.sh
osprey/fit_estimator.py
osprey/strategies.py

Refactor out sklearn.grid_search

---

osprey/config.py
osprey/data/sklearn_skeleton_config.yaml
osprey/execute_worker.py
osprey/tests/test_cli_worker_and_dump.py
osprey/tests/test_config.py

re: https://github.com/msmbuilder/osprey/issues/151

Save current best model

---

osprey/config.py
osprey/data/sklearn_skeleton_config.yaml
osprey/execute_worker.py
osprey/tests/test_cli_worker_and_dump.py
osprey/tests/test_config.py

Revert "Save current best model"

---

devtools/conda-recipe/meta.yaml

test hyperopt
